import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Khaled",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Hossam",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "2",
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 118,
      countInStock: 15,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 14,
      description: "High quality product",
    },
    {
      _id: "3",
      name: "Puma Slim Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 125,
      countInStock: 18,
      brand: "Puma",
      rating: 4.7,
      numReviews: 18,
      description: "High quality product",
    },
    {
      _id: "4",
      name: "Lacoste Slim Pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 130,
      countInStock: 20,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 8,
      description: "High quality product",
    },
    {
      _id: "5",
      name: "Nike Slim Pants",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 80,
      countInStock: 5,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "6",
      name: "Nike Straight Pants",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 60,
      countInStock: 0,
      brand: "Nike",
      rating: 4.4,
      numReviews: 16,
      description: "High quality product",
    },
  ],
};

export default data;
